# Generated by Django 4.2.7 on 2023-12-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0004_messageboardpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookclub',
            old_name='user',
            new_name='owner',
        ),
    ]
