# Generated by Django 4.2.7 on 2023-12-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0005_rename_user_bookclub_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookclub',
            old_name='owner',
            new_name='user',
        ),
    ]
